export enum AccountStatus{ACTIVE='ACTIVE',INACTIVE='INACTIVE',LOCKED='LOCKED'}
export enum VisitStatus{REGISTERED='REGISTERED',PAID='PAID',WAITING='WAITING',EXAMINING='EXAMINING',WAITING_CLS='WAITING_CLS',RESULT_READY='RESULT_READY',PRESCRIBED='PRESCRIBED',COMPLETED='COMPLETED',CANCELLED='CANCELLED'}
export enum PaymentStatus{UNPAID='UNPAID',PARTIAL='PARTIAL',PAID='PAID',REFUNDED='REFUNDED'}
export enum OrderStatus{CREATED='CREATED',AWAITING_PAYMENT='AWAITING_PAYMENT',READY='READY',IN_PROGRESS='IN_PROGRESS',COMPLETED='COMPLETED',CANCELLED='CANCELLED'}
export enum TreatmentStatus{DRAFT='DRAFT',ACTIVE='ACTIVE',COMPLETED='COMPLETED',CANCELLED='CANCELLED'}
